### ISSUE TITLE
Disconnection issue

### ISSUE THREAD

**Issue by prelol** [Job79/EasyTcp#58]
Hi,
I'm running into issues with my client.
The client works fine in a LAN, once internet is involved they send a few packages back and forth, then suddenly the BaseSocket of the client returns null. I don't directly acces the basesocket anywhere, always using the easytcp client and server to handle that for me.
On average packages are sent once every second.
Am i missing something?

Thanks in advance!
Edit: reformulated to be less verbose and more to the point.

**Comment by Job79** [comment]
Hi,
Could you share some code so I could reproduce this issue? Is it possible that the EasyTcpClient/server is getting disposed somewhere in your code?
Sending a message every 500ms should be fine, what is the size of these messages?

**Comment by prelol** [comment]
Hello, thanks for the quick reply!
I've checked all my networking code and as far as i can tell can't find any (accidental) disposing. 
Packets right now are up and around 30 bytes... doubt that could be the issue.
I've tried to boil down my code but don't see any "snippet" to be made here (its just all interlocked...)
What are possible ways the EasyTcpClient.Basesocket could become null?

**Comment by Job79** [comment]
The client socket is set to null when the .dispose method of the EasyTcpClient is called.
This method is called when a client disconnects, or when a critical internal error occurs which will also disconnect the client + call OnError. And of course when calling `.dispose()` on the client itself or when adding `using` before the client which will trigger `.dispose()` when the variable is out of scope.

Is there any exception thrown? If yes, could you share the exception + the stack trace?

**Comment by prelol** [comment]
I've got this exception, but can't trace back to when BaseSocket gets disposed
```
System.Exception
  HResult=0x80131500
  Message=Could not send data: Client not connected or null
  Source=EasyTcp3
  StackTrace:
   at EasyTcp3.Protocols.Tcp.DefaultTcpProtocol.SendMessage(EasyTcpClient client, Byte[] message)
   at BeachedBastardsBase.Network.Networking.Client.Send(EMessageType t, ISerializable package) in BeachedBastardsBase\Network\Networking\Client.cs:line 75
   at BeachedBastardsClient.Scripts.Networking.ClientSendPropertyUpdate.Send(UInt64 instanceId, EMessageType msgtypeToSend, Object value) in BeachedBastardsClient\Scripts\Networking\ClientSendPropertyUpdate.cs:line 28
   at BeachedBastardsClient.Scripts.Networking.ClientSendPropertyUpdate.SendPlayerPosition() in BeachedBastardsClient\Scripts\Networking\ClientSendPropertyUpdate.cs:line 34
   at BeachedBastardsClient.GameInput.PlayerController.Update(GameTime gameTime) in BeachedBastardsClient\GameInput\PlayerController.cs:line 69
   at BeachedBastardsClient.Scripts.Scening.GameObject.Update(GameTime gameTime) in BeachedBastardsClient\Scripts\Scening\GameObject.cs:line 66
   at BeachedBastardsClient.Scripts.Scening.Scene.Update(GameTime gameTime) in BeachedBastardsClient\Scripts\Scening\Scene.cs:line 26
   at BeachedBastardsClient.BeachedBastardsClient.Update(GameTime gameTime) in BeachedBastardsClient\BeachedBastardsClient.cs:line 85
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at BeachedBastardsClient.Program.Main() in BeachedBastardsClient\Program.cs:line 16
```

I put the EasyTcpClient in a public variable, inside Client.cs this variable is accessed through a property inside ClientPropertyUpdate, Don't see any reason why GC would ever dispose the easytcpclient. The only explicit dispose lives in a stop function, currently not even called by the program...

Any clue?

**Comment by prelol** [comment]
Facepalm... found it...
4 8 4 4 (4 4) = 28... 
MemoryStream.GetBuffer() just dumps out *your data* plus a massive buffer of 0's
it returned a small 512 bytes worth of data... every 500ms

Could this become an idiot proofing feature?
Some way to check for max packet size and throw "packet too big" or something?
I mean, "EasyTcpClient for fast and easy use" now also dummy proof!

**Comment by Job79** [comment]
> Could this become an idiot proofing feature?
> Some way to check for max packet size and throw "packet too big" or something?
> I mean, "EasyTcpClient for fast and easy use" now also dummy proof!

Yes, this is something that is already added in the develop branch and will be published with the next release.
