### ISSUE TITLE
System.Security.Cryptography.CryptographicException: m_safeCertContext is an invalid handle.

### ISSUE THREAD

**Issue by Moonbase2004** [Job79/EasyTcp#74]
When using trusted SSL Cert, client connects fine first try, but then when another connection is received, this exception is thrown.

```
Unhandled exception. System.Security.Cryptography.CryptographicException: m_safeCertContext is an invalid handle.
   at EasyTcp4.EasyTcpServer.FireOnError(Exception exception)
   at EasyTcp4.Encryption.Ssl.SslProtocol.OnConnectCallback(SocketAsyncEventArgs ar)
   at EasyTcp4.Encryption.Ssl.SslProtocol.<StartAcceptingClients>b__12_0(Object _, SocketAsyncEventArgs ar)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal()
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.AcceptCompletionCallback(IntPtr acceptedFileDescriptor, Byte[] socketAddress, Int32 socketAddressSize, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.AcceptOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.ReadOperation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Unsure if this is a bug or not, would like confirmation if it's an issue with my own code. Code:

```
public static async Task StartServer(ushort port)
        {
            uptimeTime.Start();

            try
            {
                API.LogEntry("Starting Server...", "Server");
                TCPServer.UseServerSsl(new X509Certificate2(GlobalVariables.Certificate, GlobalVariables.CertPass)).Start(port);

                if (TCPServer.IsRunning)
                {
                    uptimeTime.Stop();
                    API.LogEntry($"Server Up In {uptimeTime.ElapsedMilliseconds}ms. On Port {port}", "Server");

                    TCPServer.OnConnect += TCPServer_OnConnect;
                    TCPServer.OnDisconnect += TCPServer_OnDisconnect;
                }
                else
                {
                    API.LogEntry("Program Cannot Continue.");
                    Environment.Exit(1);
                }

                await Task.Delay(-1);
            } catch (Exception e)
            {
                API.LogEntry($"Server Failed To Start.\n{e}");
            }
        }
```

Server is running on a Linux Oracle Cloud Instance.

**Comment by Job79** [comment]
Fixed in 3b2acc81e1ce9e5dee3444c8277cb66d19023551, will publish an update when I get access to the nuget package.
